// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ColorPalettes.MockAPI.Data;

#nullable disable

namespace ColorPalettes.MockAPI.Data.Migrations
{
    [DbContext(typeof(ColorPalettesContext))]
    [Migration("20241211215618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ColorPalettes.MockAPI.Entities.Palette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Palettes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colors = "[\"#e24511\",\"#534b68\",\"#3c73a0\",\"#e75db5\"]",
                            Highlighted = true,
                            Tags = "[\"warm\",\"modern\",\"bold\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
